### ISSUE TITLE
Feature request: Add mark to small preview panel indicating the current ppem being viewed

### ISSUE THREAD

**Issue by 100amps** [psb1558/ygt#10]
It would be nice to see some sort of indicator in the bottom preview panel indicating which resolution is being displayed in the upper preview panel. Something as simple as a dot, arrowhead or underscore beneath the current one would work fine. 

<img width="353" alt="ppem_indicator" src="https://user-images.githubusercontent.com/18044808/233810791-21c50c58-3703-4713-ba44-0a7d47c8fb8a.png">

**Comment by psb1558** [comment]
I thought I might paint the glyph in a different color.

**Comment by 100amps** [comment]
I was about to respond with 'Good idea', then realized a colorblind person might not agree.

**Comment by psb1558** [comment]
I worry that a mark might, in at least a few cases, obscure part of the form that a user is looking at most closely. It is possible to adopt a [Color Blind Friendly Palette](https://venngage.com/blog/color-blind-friendly-palette/): I should probably review the color scheme for the whole app with this in mind.

**Comment by psb1558** [comment]
And this is done:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/16215767/234434256-66c63f4a-d9d4-4120-b2a9-c3830b8e48da.png">
