### ISSUE TITLE
Feature request:  press Spacebar for temporary hand/pan mode

### ISSUE THREAD

**Issue by 100amps** [psb1558/ygt#6]
This is a very useful feature in Adobe Illustrator and other graphics editors. While editing (the hints in this case), the user can press the spacebar and the operating mode changes to the Hand (pan) command until you release the spacebar.  It lets you adjust the view without interrupting your editing too much.

**Comment by psb1558** [comment]
Good idea.

**Comment by psb1558** [comment]
This is done.
