### ISSUE TITLE
Feature request: Force preview update when new glyph is opened.

### ISSUE THREAD

**Issue by 100amps** [psb1558/ygt#9]
Currently, when changing glyphs with the arrow left-right keys, the preview panel still shows the previously loaded glyph, until I edit a hint. This request is for an update of the preview panel to be triggered whenever a new glyph is loaded into the glyph window (assuming auto-update mode is active).

**Comment by psb1558** [comment]
This is done now. I had reservations about making preview update *too* automatic, since it can be slow on slow machines. But of course a user can turn it off.
